#!/bin/bash

home=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
#t=$(cat $home/default_backup.txt)
#let "t=$t-1"
for a in $(cat /usr/local/bin/default_path.txt)
do
	if echo $a | grep -q "/"; then
		backup_path=$a
	else
		p=$a
	fi
done
cd /var/games/minecraft/servers
for n in $(ls -d */ | cut -d '/' -f1)
do
	if [ -f /var/games/minecraft/servers/$n/logs/nobackup ]; then
		z=1
	else
		mkdir $backup_path/$n
		cd $backup_path/$n
		let "p1=$p+1"
		if ls | grep -q "$p"; then
			i=1
			while [[ $i -lt $p1 ]]
			do
				let "i1=$i+1"
				mv $backup_path/$n/$i $backup_path/$n/$i1
				let "i=$i+1"
			done
			rm -rf $backup_path/$n/$p1
			mkdir $backup_path/$n/1
			tar -czf $backup_path/$n/1/$n.tar.gz /var/games/minecraft/servers/$n
		else
			a=5
			while [[ $a -gt 0 ]]
			do
				if ls | grep -q $a; then
					z=1
				else
					mkdir $backup_path/$n/$a
					tar -czf $backup_path/$n/$a/$n.tar.gz /var/games/minecraft/servers/$n
					break
				fi
				let "a=$a-1"
			done
		fi
	fi
	#if [[ $change == "" ]]; then
	#	gzip -r > $backup_path/$n/
	#else
	#	if [[ $(echo $change | cut -d '-' -f1) == $(date +%Y) ]]; then
	#		if [[ $(echo $change | cut -d '-' -f2) == $(date +%m) ]]; then
	#			if [[ $(echo $change | cut -d '-' -f3) == $(date +%d) ]]; then
	#				z=1
	#			else
	#				let "a=-$(echo $change | cut -d '-' -f3)+$(date +%d)"
	#				if [[ $a -gt $t ]]; then
	#					mineos_console.js -s $n $m
	#				fi
	#			fi
	#		else
	#			let "b=-$(echo $change | cut -d '-' -f2)+$(date +%m)"
	#			if [[ $b -lt 2 ]]; then
	#				let "c=-$(echo $change | cut -d '-' -f3)+30+$(date +%d)"
	#				if [[ $c -gt $t ]]; then
	#					mineos_console.js -s $n $m
	#					fi
	#			else
	#				mineos_console.js -s $n $m
	#			fi
	#		fi
	#	else
	#		let "d=-$(echo $change | cut -d '-' -f1)+$(date +%Y)"
	#		if [[ $d -lt 2 ]]; then
	#			let "b=-$(echo $change | cut -d '-' -f2)+$(date +%m)+12"
	#			if [[ $b -lt 2 ]]; then
	#				let "c=-$(echo $change | cut -d '-' -f3)+30+$(date +%d)"
	#				if [[ $c -gt $t ]]; then
	#					mineos_console.js -s $n $m
	#				fi
	#			else
	#				mineos_console.js -s $n $m
	#			fi
	#		else
	#			mineos_console.js -s $n $m
	#		fi
	#	fi
	#fi
done