#!/bin/bash

home=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
PATH="$PATH:/usr/games/minecraft"
t=$(cat $home/default_backup.txt)
let "t=$t-1"
for m in {backup,archive}
do
cd /var/games/minecraft/$m
for n in $(ls -d */ | cut -d '/' -f1)
do
	change=$(stat $n | grep "Change:" | cut -d ":" -f2)
	if [[ $(echo $change | cut -d '-' -f1) == $(date +%Y) ]]; then
		if [[ $(echo $change | cut -d '-' -f2) == $(date +%m) ]]; then
			if [[ $(echo $change | cut -d '-' -f3) == $(date +%d) ]]; then
				z=1
			else
				let "a=-$(echo $change | cut -d '-' -f3)+$(date +%d)"
				if [[ $a -gt $t ]]; then
					mineos_console.js -s $n $m
				fi
			fi
		else
			let "b=-$(echo $change | cut -d '-' -f2)+$(date +%m)"
			if [[ $b -lt 2 ]]; then
				let "c=-$(echo $change | cut -d '-' -f3)+30+$(date +%d)"
				if [[ $c -gt $t ]]; then
					mineos_console.js -s $n $m
					fi
			else
				mineos_console.js -s $n $m
			fi
		fi
	else
		let "d=-$(echo $change | cut -d '-' -f1)+$(date +%Y)"
		if [[ $d -lt 2 ]]; then
			let "b=-$(echo $change | cut -d '-' -f2)+$(date +%m)+12"
			if [[ $b -lt 2 ]]; then
				let "c=-$(echo $change | cut -d '-' -f3)+30+$(date +%d)"
				if [[ $c -gt $t ]]; then
					mineos_console.js -s $n $m
				fi
			else
				mineos_console.js -s $n $m
			fi
		else
			mineos_console.js -s $n $m
		fi
	fi
done
done