#!/bin/bash
home=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
echo "0,5,10,15,20,25,30,35,40,45,50,55 * * * * $home/start" >> $home/crontab.txt
echo "0,5,10,15,20,25,30,35,40,45,50,55 * * * * $home/scheduled_restart_on_change" >> $home/crontab.txt
echo "0,5,10,15,20,25,30,35,40,45,50,55 * * * * $home/memory_controller" >> $home/crontab.txt
echo "0,5,10,15,20,25,30,35,40,45,50,55 * * * * $home/status_checker" >> $home/crontab.txt
echo "0,5,10,15,20,25,30,35,40,45,50,55 * * * * $home/log_handler" >> $home/crontab.txt
echo "0,5,10,15,20,25,30,35,40,45,50,55 * * * * $home/security" >> $home/crontab.txt
cat $home/crontab.txt >> /var/spool/cron/crontabs/root
chmod +x $(ls $home)