#!/bin/bash

z=0
if [ -f /usr/local/bin/home ]; then 
	home=$(cat /usr/local/bin/home)
else
	home=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
	echo $home > /usr/local/bin/home
fi
chmod -wx /usr/local/bin/home
echo "Do you want to install all of the components?(Y/N)"
while [[ z -lt 1 ]]
do
	read -n 1 k
	if [[ "$k" == "y" ]] || [[ "$k" == "Y" ]]; then
		z=1
		for a in $(cat $home/crontabs.txt)
		do
			if cat /var/spool/cron/crontabs/root | grep -q $home/$a; then
				z=1
			else
				echo "0,5,10,15,20,25,30,35,40,45,50,55 * * * * $home/$a" >> /var/spool/cron/crontabs/root
			fi
		done
		for a in $(cat $home/to_the_bin.txt)
		do
			cp $home/$a /usr/local/bin/$a
			chmod +x /usr/local/bin/$a
		done
		chmod +x $(ls)
		echo "Your clone is now updated/installed!"
	else
		if [[ "$k" == "n" ]] || [[ "$k" == "N" ]]; then
			z=1
			touch $home/missingcrontabs.txt
			for a in  $(cat $home/crontabs.txt)
			do
				if cat /var/spool/cron/crontabs/root | grep -q $home/$a; then
					t=1
				else
					echo $a >> $home/missingcrontabs.txt
				fi
			done
			if [ -s $home/missingcrontabs.txt ]; then
				echo " "
				echo "Please define which scripts do you want to crontab.(They will be ran every 5 minutes)"
				for a in $(cat $home/missingcrontabs.txt)
				do
					echo " "
					echo "$a?(Y/N)"
					z=0
					while [[ z -lt 1 ]]
					do
						read -n 1 k
						if [[ "$k" == "y" ]] || [[ "$k" == "Y" ]]; then
							z=1
							echo "0,5,10,15,20,25,30,35,40,45,50,55 * * * * $home/$a" >> /var/spool/cron/crontabs/root
							if [[ $a == "scheduled_restart_on_change" ]]; then
								echo "Please define when do you want to restart your server on change in seconds or in hh:mm format or leave it bank for default. (The default is 7200 seconds)"
								read timer
								if [[ $timer == "" ]]; then
									t=1
								else
									echo $timer &> $home/default_timer.txt
								fi
							fi
							if [[ $a == "auto_backup" ]]; then
								echo "Please define which time interval you want to back up your servers in days. Leave it blank for default. (The default is 5 days)"
								read days
								if [[ $days == "" ]]; then
									t=1
								else
									echo $days &> $home/default_backup.txt
								fi
							fi
						else
							if [[ "$k" == "n" ]] || [[ "$k" == "N" ]]; then
								z=1
							fi
						fi
					done
				done
			fi
			rm $home/missingcrontabs.txt
			echo " "
			echo "Please define for each script if you want them in your default path folder so you will be able to call them just by their name in the terminal."
			for a in $(cat $home/to_the_bin.txt)
			do
				echo " "
				echo "$a?(Y/N)"
				z=0
				while [[ z -lt 1 ]]
				do
					read -n 1 k
					if [[ "$k" == "y" ]] || [[ "$k" == "Y" ]]; then
						z=1
						cp $home/$a /usr/local/bin/$a
						chmod +x /usr/local/bin/$a
					else
						if [[ "$k" == "n" ]] || [[ "$k" == "N" ]]; then
							z=1
						fi
					fi
				done
			done
			chmod +x $(ls)
			echo " "
			echo "Your clone is now updated/installed!"
		fi
	fi
done