#!/bin/bash

z=0
IFS=$'\n'
if [ -f /usr/local/bin/home ]; then 
	home=$(cat /usr/local/bin/home)
else
	home=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
	echo $home > /usr/local/bin/home
fi
chmod -wx /usr/local/bin/home
echo "Do you want to install all of the components?(Y/N)"
while [[ z -lt 1 ]]
do
	read -n 1 k
	if [[ "$k" == "y" ]] || [[ "$k" == "Y" ]]; then
		z=1
		for a in $(cat $home/crontabs.txt)
		do
			if cat /var/spool/cron/crontabs/root | grep -q $home/$a; then
				z=1
			else
				if [[ $a == "auto_backup" ]]; then
					touch /usr/local/bin/default_path.txt
					if [[ $(cat /usr/local/bin/default_path.txt) == "" ]]; then
						echo "Please define the default backup path:"
						read backup_path
						echo $backup_path > /usr/local/bin/default_path.txt
						echo ""
						echo "Please define how many backups you want to keep:"
						read k
						echo $k >> /usr/local/bin/default_path.txt
						echo ""
					fi
					echo "Please define which time interval should it run in the format of each x-th day. (only write the x)"
					read korte
					kortes=1
					while [[ $kortes -lt 29 ]]
					do
						if [[ $kort == "" ]]; then
							kort=$kortes
						else
							kort="$kort,$kortes"
						fi
						let "kortes=$kortes+$korte"
					done
					echo "* * $kort * * $home/$a" >> /var/spool/cron/crontabs/root
				else
					echo "0,5,10,15,20,25,30,35,40,45,50,55 * * * * $home/$a" >> /var/spool/cron/crontabs/root
				fi
			fi
		done
		for a in $(cat $home/to_the_bin.txt)
		do
			cp $home/$a /usr/local/bin/$a
			chmod +x /usr/local/bin/$a
		done
		chmod +x $(ls)
		echo "Your clone is now updated/installed!"
	else
		if [[ "$k" == "n" ]] || [[ "$k" == "N" ]]; then
			z=1
			touch $home/missingcrontabs.txt
			for a in  $(cat $home/crontabs.txt)
			do
				if cat /var/spool/cron/crontabs/root | grep -q $home/$a; then
					t=1
				else
					echo $a >> $home/missingcrontabs.txt
				fi
			done
			if [ -s $home/missingcrontabs.txt ]; then
				echo " "
				echo "Please define which scripts do you want to crontab.(They will be ran every 5 minutes)"
				for a in $(cat $home/missingcrontabs.txt)
				do
					echo " "
					echo "$a?(Y/N)"
					z=0
					while [[ z -lt 1 ]]
					do
						read -n 1 k
						if [[ "$k" == "y" ]] || [[ "$k" == "Y" ]]; then
							z=1
							if [[ $a == "auto_backup" ]]; then
								touch /usr/local/bin/default_path.txt
								if [[ $(cat /usr/local/bin/default_path.txt) == "" ]]; then
									echo "Please define the default backup path:"
									read backup_path
									echo $backup_path > /usr/local/bin/default_path.txt
									echo ""
									echo "Please define how many backups you want to keep:"
									read k
									echo $k >> /usr/local/bin/default_path.txt
									echo ""
								fi
								echo "Please define which time interval should it run in the format of each x-th day"
								read korte
								while [[ $kortes -lt 29 ]]
								do
									if [[ $kort == "" ]]; then
										kort=$kortes
									else
										kort="$kort,$kortes"
									fi
									let "kortes=$kortes+$korte"
								done
								echo "* * $kort * * $home/$a" >> /var/spool/cron/crontabs/root
							else
								echo "0,5,10,15,20,25,30,35,40,45,50,55 * * * * $home/$a" >> /var/spool/cron/crontabs/root
								if [[ $a == "scheduled_restart_on_change" ]]; then
									echo "Please define when do you want to restart your server on change in seconds or in hh:mm format or leave it bank for default. (The default is 7200 seconds)"
									read timer
									if [[ $timer == "" ]]; then
										t=1
									else
										echo $timer &> $home/default_timer.txt
									fi
								fi
							fi
						else
							if [[ "$k" == "n" ]] || [[ "$k" == "N" ]]; then
								z=1
							fi
						fi
					done
				done
			fi
			rm $home/missingcrontabs.txt
			echo " "
			echo "Please define for each script if you want them in your default path folder so you will be able to call them just by their name in the terminal."
			for a in $(cat $home/to_the_bin.txt)
			do
				echo " "
				echo "$a?(Y/N)"
				z=0
				while [[ z -lt 1 ]]
				do
					read -n 1 k
					if [[ "$k" == "y" ]] || [[ "$k" == "Y" ]]; then
						z=1
						cp $home/$a /usr/local/bin/$a
						chmod +x /usr/local/bin/$a
					else
						if [[ "$k" == "n" ]] || [[ "$k" == "N" ]]; then
							z=1
						fi
					fi
				done
			done
			chmod +x $(ls)
			echo " "
			echo "Your clone is now updated/installed!"
		fi
	fi
done
echo "Do you want to start mc_command_handler? (If it already ran then this will restart it) [Y/N]"
z=0
while [[ z -lt 1 ]]
do
	read -n 1 k
	if [[ "$k" == "y" ]] || [[ "$k" == "Y" ]]; then
		z=1
		for i in $(ps -eaf | grep "$(ps -eaf | grep "/var/games/minecraft/servers/.*/logs" | tr -s ' ' | cut -d ' ' -f3)" | tr -s ' ' | cut -d ' ' -f2)
		do
			kill $i
		done
		kill $(ps -eaf | grep "/bin/bash .*/mc_command_handler" | tr -s ' ' | cut -d ' ' -f2)
		($home/mc_command_handler)&
	else
		if [[ "$k" == "n" ]] || [[ "$k" == "N" ]]; then
			z=1
		fi
	fi
done
echo "Please write here your ip"
read k
echo "server-ip=$k" >> $home/default_props.txt
echo "Do you want to start server_prop_changer? (If it already ran then this will restart it) [Y/N]"
z=0
while [[ z -lt 1 ]]
do
	read -n 1 k
	if [[ "$k" == "y" ]] || [[ "$k" == "Y" ]]; then
		z=1
		for i in $(ps -eaf | grep "$(ps -eaf | grep "/var/games/minecraft/servers/.*/ran" | tr -s ' ' | cut -d ' ' -f3)" | tr -s ' ' | cut -d ' ' -f2)
		do
			kill $i
		done
		($home/server_prop_changer)&
	else
		if [[ "$k" == "n" ]] || [[ "$k" == "N" ]]; then
			z=1
		fi
	fi
done