#!/bin/bash

home=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
rm /var/games/minecraft/servers/*/logs/running
PATH="$PATH:/usr/games/minecraft"
cd /var/games/minecraft/servers
while (true)
do
	for oname in $(ls -d */)
	do
		name=$(echo $oname | cut -d '/' -f1)
		if [ -f /var/games/minecraft/servers/$name/logs/running ] || [ -f /var/games/minecraft/servers/$name/logs/notup ]; then
			z=1
		else
			touch /var/games/minecraft/servers/$name/logs/running
			(if tail -F -n 0 /var/games/minecraft/servers/$name/logs/latest.log | grep -q ".*Server thread/INFO.* <.*> #"; then 
				user=$(tail -n 1 /var/games/minecraft/servers/$name/logs/latest.log | cut -d '<' -f2 | cut -d '>' -f1)
				if id "$user" >/dev/null 2>&1; then
					runuser -l $user -c "$(tail -n 1 /var/games/minecraft/servers/$name/logs/latest.log | cut -d '>' -f2 | cut -d '#' -f2 )" &> /var/games/minecraft/servers/temp$name.txt 
					IFS=$'\n'
					for t in $(cat /var/games/minecraft/servers/temp$name.txt)
					do
						mineos_console.js -s $name stuff "say $t"
					done
				else
					mineos_console.js -s $name stuff "say You do not have permission to use linux-side commands."
				fi
				rm /var/games/minecraft/servers/$name/logs/running
			fi)&
		fi
	done
	sleep 1
done