#!/bin/bash

IFS=$'\n'
for server_name in $(ps -eo rss,ppid,pid,comm | grep "java")
do
namee=$(ps -eo pid,args | grep $(echo $server_name | tr -s ' ' | cut -d ' ' -f2) | perl -pe 's/^\s+//' | tr -s ' ' | cut -d ' ' -f10 | perl -pe 's/^\s+//')
if [[ $namee == *forge*universal.jar* ]] || [[ $namee == *minecraft*server*.jar* ]]; then
name=$(ps -eo pid,args | grep $(echo $server_name | tr -s ' ' | cut -d ' ' -f2) | perl -pe 's/^\s+//' | tr -s ' ' | cut -d ' ' -f4 | cut -d '-' -f2)
memory=$(echo $server_name | tr -s ' ' | cut -d ' ' -f1 | awk '{ hr=$1/1024 ; printf("%13.0f",hr) } { for ( x=4 ; x<=NF ; x++ ) { printf("%s ",$x) } print "" }' | perl -pe 's/^\s+//')
max_mem1=$(ps -eo pid,args | grep $(echo $server_name | tr -s ' ' | cut -d ' ' -f2) | perl -pe 's/^\s+//'  | tr -s ' ' | cut -d ' ' -f7 | cut -d 'x' -f2 | cut -d 'M' -f1)
memper=1
let "memper=$memory*100/$max_mem1"
let "max_mem=$max_mem1*93/100"
cd /usr/games/minecraft
(if [[ $memory -gt $max_mem ]]; then
touch /var/games/minecraft/servers/$name/logs/restarting
echo "$(date +%c) $name $memory/$max_mem1   $memper%" >> /var/games/minecraft/log.txt
./mineos_console.js -s $name stuff "say The server will restart in 2 minutes due to memory overload, $memper%"
sleep 60
./mineos_console.js -s $name stuff "say 1 minute left"
sleep 30
for i in {0..29}
do
let "a=30-$i"
./mineos_console.js -s $name stuff "say $a seconds"
sleep 1
done
./mineos_console.js -s $name restart
fi)&
fi
done