#!/bin/bash

if [[ "$1" == "" ]]; then
echo "szerver neve            jelenlegi memoria/max memoria"
IFS=$'\n'
for server_name in $(ps -eo rss,ppid,pid,comm | grep "java")
do
namee=$(ps -eo pid,args | grep $(echo $server_name | tr -s ' ' | cut -d ' ' -f2) | perl -pe 's/^\s+//' | tr -s ' ' | cut -d ' ' -f10 | perl -pe 's/^\s+//')
if [[ $namee == *forge*universal.jar* ]] || [[ $namee == *minecraft*server*.jar* ]]; then 
name=$(ps -eo pid,args | grep $(echo $server_name | tr -s ' ' | cut -d ' ' -f2) | perl -pe 's/^\s+//' | tr -s ' ' | cut -d ' ' -f4 | cut -d '-' -f2)
memory=$(echo $server_name | tr -s ' ' | cut -d ' ' -f1 | awk '{ hr=$1/1024 ; printf("%13.0f",hr) } { for ( x=4 ; x<=NF ; x++ ) { printf("%s ",$x) } print "" }' | perl -pe 's/^\s+//')
max_mem=$(ps -eo pid,args | grep $(echo $server_name | tr -s ' ' | cut -d ' ' -f2) | perl -pe 's/^\s+//'  | tr -s ' ' | cut -d ' ' -f7 | cut -d 'x' -f2 | cut -d 'M' -f1)
test=1
per=1
let "test=$max_mem*75/100"
let "per=$memory*100/$max_mem"
let "max_mem=$max_mem*9/10"


echo "$name                             $memory/$max_mem      $per%"
fi
done
else
if [[ "$1" == "log" ]]; then 
cat /var/games/minecraft/log.txt 
else
echo "Bad argument. Use 'log' to print out the restart log."
fi
fi
