#!/bin/bash

home=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
IFS=$'\n'
msg="$1"
msg_content=\"$msg\"
for url in $(cat $home/url.txt)
do
curl -H "Content-Type: application/json" -X POST -d "{\"content\": $msg_content}" $url
done