#!/bin/bash

home=$(cat /usr/local/bin/home)
if [[ $1 == "-c" ]]; then
	cd /var/games/minecraft/servers
	for a in $home/used_ports.txt
	do
		if ls -d */ | cut -d "/" -f1 | grep -q $(echo $a | cut -d "-" -f1); then
			echo $a >> temp_ports.txt
		else
			iptables -D INPUT -p tcp -m tcp --dport $(echo $a | cut -d "-" -f3) -j ACCEPT
			iptables-save > /etc/iptables-rules
			iptables-restore < /etc/iptables-rules
		fi
	done
	if [[ $(cat $home/temp_ports.txt) == "" ]]; then
	z=1
	else
		rm $home/used_ports.txt
		cp $home/temp_ports.txt $home/used_ports.txt
		rm $home/temp_ports.txt
		chmod +rw $home/used_ports.txt
	fi
else
	echo "These are the server names with their ports:"
	for i in $(cat $home/used_ports.txt)
	do
		echo $i
	done
fi