#!/bin/bash

home=$(cat /usr/local/bin/home)
IFS=$'\n'
if [[ $1 == "-c" ]]; then
	cd /var/games/minecraft/servers
	for a in $(cat $home/used_ports.txt)
	do
		if ls -d */ | cut -d "/" -f1 | grep -q $(echo $a | cut -d "-" -f1); then
			echo $a >> $home/temp_ports.txt
		else
			iptables -D INPUT -p tcp -m tcp --dport $(echo $a | cut -d "-" -f3) -j ACCEPT
			iptables-save > /etc/iptables-rules
			iptables-restore < /etc/iptables-rules
		fi
	done
	for a in $(ls -d */ | cut -d '/' -f1)
	do
		h=$(cat /var/games/minecraft/servers/$a/server.properties | grep "port" | cut -d "=" -f2 | cut -d ' ' -f1)
		l="$a-$h"
		echo $l>> $home/temp_ports.txt
	done
	if [[ $(cat $home/temp_ports.txt) == "" ]]; then
		z=1
	else
		rm $home/used_ports.txt
		cp $home/temp_ports.txt $home/used_ports.txt
		rm $home/temp_ports.txt
		chmod +rw $home/used_ports.txt
	fi
	for a in $(iptables --list)
	do
		if echo $a | cut -d " " -f1 | grep -q "ACCEPT"; then 
			if echo $a | cut -d ":" -f2 | grep -q "255.*"; then
				if cat $home/used_ports.txt | grep -q $(echo $a | cut -d ":" -f2); then
					z=1
				else
					iptables -D INPUT -p tcp -m tcp --dport $(echo $a | cut -d ":" -f2) -j ACCEPT
					iptables-save > /etc/iptables-rules
					iptables-restore < /etc/iptables-rules
				fi
			fi
		fi 
	done
else
	echo "These are the server names with their ports:"
	for i in $(cat $home/used_ports.txt)
	do
		echo $i
	done
fi