#!/bin/bash

PATH="$PATH:/usr/games/minecraft"
for n1 in $(ls -d */)
do
	n=$(echo $oname | cut -d '/' -f1)
	if [ -f /var/games/minecraft/servers/$n/server_prop.sha1 ]; then
		if sha1sum -c /var/games/minecraft/servers/$n/server_prop.sha1; then
			z=1
		else
			if [ -f ./default_timer.txt] && [[ cat ./default_timer.txt !="" ]]; then
				(./timer $n $(cat ./default_time.txt))&
			else
				mineos_console.js -s $n stuff "say Please define when do you want to restart the server! \n Give the delta time in seconds or the exact time as hh:mm (use 24h format)"
				a=0
				(while (a -eq 0)
				do
					if tail -F -n 0 /var/games/minecraft/servers/$n/logs/latest.log | grep -q ".*Server thread/INFO.* <.*> #"; then 
						user=$(tail -n 1 /var/games/minecraft/servers/$n/logs/latest.log | cut -d '<' -f2 | cut -d '>' -f1)
						if id "$user" >/dev/null 2>&1; then
							(./timer $n "$(tail -n 1 /var/games/minecraft/servers/$n/logs/latest.log | cut -d '>' -f2 | cut -d '#' -f2 )")&
							a=1
						else
							mineos_console.js -s $n stuff "say You do not have permission to tell when to restart the server!"
						fi
						rm /var/games/minecraft/servers/$n/logs/running
					fi
				done)&
			fi
		fi
	else
		sha1sum /var/games/minecraft/servers/$n/server.properties > /var/games/minecraft/servers/$n/server_prop.sha1
	fi
done