#!/bin/bash

home=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
PATH="$PATH:/usr/games/minecraft"
cd /var/games/minecraft/servers
for n1 in $(ls -d */)
do
	n=$(echo $n1 | cut -d '/' -f1)
	if [ -f /var/games/minecraft/servers/$n/logs/mods.data ]; then
		if [ -f /var/games/minecraft/servers/$n/logs/configs.data ]; then
			for a in $(cat /var/games/minecraft/servers/$n/logs/mods.data)
			do
				x=0
				for b in $(ls -lh /var/games/minecraft/servers/$n/mods)
				do
					if [ $a==$b ]; then
						x=1
					else
						let "x=$x+1"
					fi
				done
				if [ $x==0 ]; then
					break;
				fi
			done
			
		for c in $(cat /var/games/minecraft/servers/$n/logs/configs.data)
			do
				y=0
				for d in $(ls -lh /var/games/minecraft/servers/$n/config)
				do
					if [ $c==$d ]; then
						y=1
					else
						let "y=$y+1"
					fi
				done
				if [ $y==0 ]; then
					break;
				fi
			done
		else
			$(ls -lh /var/games/minecraft/servers/$n/config) > /var/games/minecraft/servers/$n/logs/configs.data
		fi
	else
		$(ls -lh /var/games/minecraft/servers/$n/mods) > /var/games/minecraft/servers/$n/logs/mods.data
	fi
	
	
	
	if [ -f /var/games/minecraft/servers/$n/server_prop.sha1 ]; then
		if sha1sum -c /var/games/minecraft/servers/$n/server_prop.sha1 || [ $x==1 ] || [ $y==1 ]; then
			z=1
		else
			if [ -f $home/default_timer.txt ]; then
				if [[ $(cat $home/default_timer.txt) != "" ]]; then
					(./timer $n $(cat $home/default_time.txt))&
					sha1sum /var/games/minecraft/servers/$n/server.properties > /var/games/minecraft/servers/$n/server_prop.sha1
					$(ls -lh /var/games/minecraft/servers/$n/config) > /var/games/minecraft/servers/$n/logs/configs.data
					$(ls -lh /var/games/minecraft/servers/$n/mods) > /var/games/minecraft/servers/$n/logs/mods.data
				fi
			else
				mineos_console.js -s $n stuff "say Please define when do you want to restart the server! \n Give the delta time in seconds or the exact time as hh:mm (use 24h format)"
				a=0
				(while (a -eq 0)
				do
					if tail -F -n 0 /var/games/minecraft/servers/$n/logs/latest.log | grep -q ".*Server thread/INFO.* <.*> #"; then 
						user=$(tail -n 1 /var/games/minecraft/servers/$n/logs/latest.log | cut -d '<' -f2 | cut -d '>' -f1)
						if id "$user" >/dev/null 2>&1; then
							(./timer $n "$(tail -n 1 /var/games/minecraft/servers/$n/logs/latest.log | cut -d '>' -f2 | cut -d '#' -f2 )")&
							a=1
							sha1sum /var/games/minecraft/servers/$n/server.properties > /var/games/minecraft/servers/$n/server_prop.sha1
							$(ls -lh /var/games/minecraft/servers/$n/config) > /var/games/minecraft/servers/$n/logs/configs.data
							$(ls -lh /var/games/minecraft/servers/$n/mods) > /var/games/minecraft/servers/$n/logs/mods.data
						else
							mineos_console.js -s $n stuff "say You do not have permission to tell when to restart the server!"
						fi
					fi
				done)&
			fi
		fi
	else
		sha1sum /var/games/minecraft/servers/$n/server.properties > /var/games/minecraft/servers/$n/server_prop.sha1
	fi
done