#!/bin/bash

home=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
PATH="$PATH:/usr/games/minecraft"
cd /var/games/minecraft/servers
for n1 in $(ls -d */)
do
	n=$(echo $n1 | cut -d '/' -f1)
	if [ -f /var/games/minecraft/servers/$n/logs/mods.data ]; then
		if [ -f /var/games/minecraft/servers/$n/logs/configs.data ]; then
			for a in $(cat /var/games/minecraft/servers/$n/logs/mods.data)
			do
				x=0
				for b in $(ls -lh /var/games/minecraft/servers/$n/mods)
				do
					if [ $a==$b ]; then
						x=1
					else
						let "x=$x+1"
					fi
				done
				if [ $x==0 ]; then
					break;
				fi
			done
			
		for c in $(cat /var/games/minecraft/servers/$n/logs/configs.data)
			do
				y=0
				for d in $(ls -lh /var/games/minecraft/servers/$n/config)
				do
					if [ $c==$d ]; then
						y=1
					else
						let "y=$y+1"
					fi
				done
				if [ $y==0 ]; then
					break;
				fi
			done
		else
			if [ -f /var/games/servers/$n/config ]; then
				echo $(ls -lh /var/games/minecraft/servers/$n/config) > /var/games/minecraft/servers/$n/logs/configs.data
			fi
		fi
	else
		if [ -f /var/games/minecraft/servers/$n/mods ]; then
			echo $(ls -lh /var/games/minecraft/servers/$n/mods) > /var/games/minecraft/servers/$n/logs/mods.data
		fi
	fi
	
	
	
	if [ -f /var/games/minecraft/servers/$n/server_prop.sha1 ]; then
		if sha1sum -c /var/games/minecraft/servers/$n/server_prop.sha1 | grep -q FAILED || [[ $x != 1 ]] || [[ $y != 1 ]]; then
			if [ -f $home/default_timer.txt ]; then
				if [[ $(cat $home/default_timer.txt) != "" ]]; then
					(./timer $n $(cat $home/default_time.txt))&
					sha1sum /var/games/minecraft/servers/$n/server.properties > /var/games/minecraft/servers/$n/server_prop.sha1
					echo $(ls -lh /var/games/minecraft/servers/$n/config) > /var/games/minecraft/servers/$n/logs/configs.data
					echo $(ls -lh /var/games/minecraft/servers/$n/mods) > /var/games/minecraft/servers/$n/logs/mods.data
				else
					./mineos_console.js -s $n stuff "say Please define a default timer at $home/default_timer.txt in the format of seconds!"
				fi
			else
				./mineos_console.js -s $n stuff "say Please define a default timer at $home/default_timer.txt in the format of seconds!"
			fi
		fi
	else
		sha1sum /var/games/minecraft/servers/$n/server.properties > /var/games/minecraft/servers/$n/server_prop.sha1
	fi
done