#!/bin/bash

home=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
cd /var/games/minecraft/servers
for n1 in $(ls -d */)
do
n=$(echo $n1 | cut -d '/' -f1)
if cat /var/games/minecraft/servers/$n/server.properties | grep -q "online-mode=false"; then
/usr/games/minecraft/mineos_console.js -s $n stuff "/ban root"
fi
done