#!/bin/bash
home=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
IFS=$'\n'
if [[ $1 == "-f" ]]; then
	cd /var/games/minecraft/servers/
	rm $home/used_ports.txt
	touch $home/used_ports.txt
	for n in $(ls -d */ | cut -d '/' -f1)
	do
		bool=0
		while [[ bool -lt 1 ]]
		do
			port=$(shuf -i 25500-25600 -n 1)
			if netstat -tulpn | grep LISTEN | grep -q $port || cat $home/used_ports.txt | grep -q $port; then
				bool=0
			else
				bool=1
			fi
		done
		for a in $(cat /var/games/minecraft/servers/$n/server.properties)
		do
			if echo $a | grep -q "server-port"; then
				a="$(echo $a | cut -d "=" -f1)=$port"
				echo $a >> /var/games/minecraft/servers/$n/server.temp
				serverport="$n--$port"
				if iptables --list | grep -q "Chain INPUT (policy ACCEPT)"; then
					z=1
				else
					echo $serverport >> $home/used_ports.txt
					iptables -A INPUT -p tcp -m tcp --dport $port -j ACCEPT
					iptables-save > /etc/iptables-rules
					iptables-restore < /etc/iptables-rules
				fi
			else
				if cat $home/default_props.txt | grep -q $(echo $a | cut -d "=" -f1); then
					cat $home/default_props.txt | grep $( echo $a | cut -d '=' -f1) >> /var/games/minecraft/servers/$n/server.temp
				else
					echo $a >> /var/games/minecraft/servers/$n/server.temp
				fi
			fi
		done
		for a in $(cat $home/default_props.txt)
		do
			if cat /var/games/minecraft/servers/$n/server.temp | grep -q $(echo $a | cut -d '=' -f1); then
				z=1
			else
				echo $a >> /var/games/minecraft/servers/$n/server.temp
			fi
		done
		rm /var/games/minecraft/servers/$n/server.properties
		cp /var/games/minecraft/servers/$n/server.temp /var/games/minecraft/servers/$n/server.properties
		rm /var/games/minecraft/servers/$n/server.temp
		chmod a+rwx /var/games/minecraft/servers/$n/server.properties
		touch /var/games/minecraft/servers/$n/logs/ran
	done
else
while (true)
do
	cd /var/games/minecraft/servers/
	for n in $(ls -d */ | cut -d '/' -f1)
	do
		if [ -f /var/games/minecraft/servers/$n/logs/ran ]; then
			z=1
		else
			bool=0
			while [[ bool -lt 1 ]]
			do
				port=$(shuf -i 25500-25600 -n 1)
				if netstat -tulpn | grep LISTEN | grep -q $port || cat $home/used_ports.txt | grep -q $port; then
					bool=0
				else
					bool=1
				fi
			done
			for a in $(cat /var/games/minecraft/servers/$n/server.properties)
			do
				if echo $a | grep -q "server-port"; then
					a="$(echo $a | cut -d "=" -f1)=$port"
					echo $a >> /var/games/minecraft/servers/$n/server.temp
					serverport="$n--$port"
					echo $serverport >> $home/used_ports.txt
					iptables -A INPUT -p tcp -m tcp --dport $port -j ACCEPT
					iptables-save > /etc/iptables-rules
					iptables-restore < /etc/iptables-rules
				else
					if cat $home/default_props.txt | grep -q $(echo $a | cut -d "=" -f1); then
						cat $home/default_props.txt | grep $( echo $a | cut -d '=' -f1) >> /var/games/minecraft/servers/$n/server.temp
					else
						echo $a >> /var/games/minecraft/servers/$n/server.temp
					fi
				fi
			done
			for a in $(cat $home/default_props.txt)
			do
				if cat /var/games/minecraft/servers/$n/server.temp | grep -q $(echo $a | cut -d '=' -f1); then
					z=1
				else
					echo $a >> /var/games/minecraft/servers/$n/server.temp
				fi
			done
			rm /var/games/minecraft/servers/$n/server.properties
			cp /var/games/minecraft/servers/$n/server.temp /var/games/minecraft/servers/$n/server.properties
			rm /var/games/minecraft/servers/$n/server.temp
			chmod a+rwx /var/games/minecraft/servers/$n/server.properties
			touch /var/games/minecraft/servers/$n/logs/ran
		fi
	done
	sleep 1
done
fi