#!/bin/bash

z=0
if [[ "$1" == "" ]]; then
	echo "These servers are part of the restart table:"
	for i in $(cat ./data.txt)
	do
		echo "$i"
	done
else
	if cat ./data.txt | grep -w -q "$1"; then
		if [[ "$2" == "" ]]; then
			echo " The $1 server is part of the restart table.${reset}"
		else
			if [[ "$2" == "remove" ]]; then
				if [ "$3" == "" ]; then
					echo " This operation will remove the $1 server from the restart table. Are you sure you want to continue? (y/n) "
					while [ $z -eq 0 ]
					do
						read -n 1 k
						if [[ "$k" == "y" ]] || [[ "$k" == "Y" ]]; then
							for a in $(cat ./data.txt)
							do
								if [[ "$a" != "$1" ]]; then 
									echo $a >> ./data1.txt
								fi
							done
							rm ./data.txt
							cp ./data1.txt ./data.txt
							rm ./data1.txt
							echo "The $1 server is removed from the list. "
							z=1
						else
							if [[ "$k" == "n" ]] || [[ "$k" == "N" ]]; then
								echo " The operation is cancelled by the user. "
								exit 0
							fi
						fi
					done
				else
					if [ "$3" == "y" ] || [ "$3" == "Y" ]; then
						for a in $(cat ./data.txt)
						do
							if [[ "$a" != "$1" ]]; then 
								echo $a >> ./data1.txt
							fi
						done
						rm ./data.txt
						cp ./data1.txt ./data.txt
						rm ./data1.txt
						echo "The $1 server is removed from the list. "
					fi
				fi
			else
				if [[ "$2" == "add" ]]; then
					echo "The $1 server is already part of the restart table. "
				else
					echo "The second argument is wrong. Use the 'add' or 'remove' arguments to add or remove a server to or from the restart table respectively. "
					exit 3
				fi
			fi
		fi
	else
		if [[ "$2" == "" ]]; then
			echo "The $1 server is not part of the restart table yet. "
		else
			if [[ "$2" == "add" ]]; then
				echo $1 >>  ./data.txt
				echo "The $1 server is added to the restart table... If it does not restart properly or is shut down by any action it will automatically restart. "
			else
				if [[ "$2" == "remove" ]]; then
					echo "The $1 server is not part of the restart table yet so you can't remove it. "
				else
					echo "The second argument is wrong. Use the 'add' or 'remove' arguments to add or remove a server to or from the restart table respectively. "
					exit 3
				fi
			fi
		fi
	fi
fi
