#!/bin/bash

cd /usr/games/minecraft
for name in $(cat ./data.txt)
do
if [[ $(./mineos_console.js -s $name up | tr -s ' ' | cut -d ' ' -f5) != "true" ]]; then
./mineos_console.js -s $name start
fi
done