#!/bin/bash

home=/var/games/minecraft
cd /usr/games/minecraft
for name in $(cat /var/games/minecraft/data.txt)
do
if [[ $(./mineos_console.js -s $name up | tr -s ' ' | cut -d ' ' -f5) != "true" ]]; then
./mineos_console.js -s $name start
fi
done