#!/bin/bash

PATH="$PATH:/usr/games/minecraft"
if echo $2 | grep -q ":"; then
	s=0
	let "h=$(echo $2 | cut -d ':' -f1)-$(date +%H)"
	let "m=$(echo $2 | cut -d ':' -f2)-$(date +%M)"
	let "s=$h*3600+$m*60"
else
	s=$2
fi
if [[ $s -lt 1 ]]; then 
let "s=$s+24*3600"
fi
let "s=$s+1"
while [[ $i -lt $s ]]
do
	let "e=$s-$i"
	let "h1=$e/3600"
	let "m1=$e/60"
	if [ h1==h2 ] && [ m1==m2 ]; then
		sleep 1
	else 
		if [[ $e -gt 3600 ]]; then
			mineos_console.js -s $1 stuff "say The server will restart in $h1 hours!"
			h2=$h1
		else
			if [[ $e -gt 60 ]]; then
				mineos_console.js -s $1 stuff "say The server will restart in $m1 minutes!"
				m2=$m1
			fi
		fi
	fi
	if [[ $e -lt 60 ]]; then
		mineos_console.js -s $1 stuff "say The server will restart in $e seconds!"
		sleep 1
	fi
	if [[ $e==1 ]]; then
		sleep 1
		mineos_console.js -s $1 restart
	fi
	if [ -f /var/games/minecraft/servers/$name/logs/restarting ]; then
		break
	fi
	mineos_console.js -s $1 stuff "/list"
	if tail -n 1 /var/games/minecraft/servers/$1/logs/latest.log | cut -d 'o' -f1 | grep -q "0"; then
		mineos_console.js -s $1 restart
		break
	fi
	let "i=$i+1"
done
