#!/bin/bash
if [ -f /usr/local/bin/home ]; then 
home=$(cat /usr/local/bin/home)
else
home=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
echo $home > /usr/local/bin/home
fi
chmod -wx /usr/local/bin/home
cd $home
git fetch --all
git reset --hard origin/master
chmod +x $home/installer
$home/installer